name: autorelease

on:
  pull_request:
    types: [closed] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Pull request merged
      if: github.event.pull_request.merged == true && contains(toJSON(github.event.pull_request.*.name), '"autorelease"')
      run: echo merged
